const HUAWEI_G2_KEY_PARAMAETERS = `
SELECT
t1."DATETIME" AS "DATETIME",
t2."SYSOBJECTID" as "NENAME",
'HUAWEI' AS "VENDOR",
'2G' AS "TECHNOLOGY",
t3."BTSNAME" AS "SITENAME",
t3."BTSID" AS "SITEID",
t1."CELLNAME" AS "CELLNAME",
t1."ACTSTATUS" AS "ACTSTATUS",
t1."ADMSTAT" AS "BLKSTATUS",
t1."MCC" AS "MCC",
t1."MNC" AS "MNC",
t1."LAC" AS "LAC",
t1."CI" AS "CI",
t1."BCCHNO" AS "BCCHNO",
t1."NCC" AS "NCC",
t1."BCC" AS "BCC",
CONCAT(t1."NCC", t1."BCC") AS "BSIC",
CONCAT(t1."MCC", '-', t1."MNC", '-', t1."LAC", '-', t1."CI") AS "CGI_RAW",
CONCAT(t1."MCC", '-', t1."MNC", '-', LPAD(t1."LAC",5,'0'), '-', t1."CI") AS "CGI"
FROM huawei_cm."GCELL" t1
INNER JOIN huawei_cm."SYS" t2 ON t1."FILENAME" = t2."FILENAME"
INNER JOIN huawei_cm."BTS" t3 ON t3."BTSID" = t1."BTSID" AND t1."FILENAME" = t3."FILENAME"
`;