export const VENDOR_CM_FORMATS = {
	'ERICSSON': ['BULKCM','CNAIV2','BSM','EAW'],
	'HUAWEI': ['GEXPORT_XML','NBI_XML','CFGMML', 'AUTOBAK_XML'],
	'ZTE': ['BULKCM','XLS'],
	'NOKIA': ['RAML'],
	'MOTOROLA': ['CELL_X_EXPORT'],
	'BODASTAGE': ['BCF_CSV']
}

export const VENDOR_PM_FORMATS = {
	'ERICSSON': ['MEAS_COLLEC_XML'],
	'HUAWEI': ['NE_BASED_MEAS_COLLEC_XML'],
	'ZTE': ['MEAS_COLLEC_XML','EXCEL'],
	'NOKIA': ['PM_XML'],
	'MOTOROLA': [],
	'BODASTAGE': ["CSV","EXCEL"]
}

export const VENDOR_FM_FORMATS = {
	'ERICSSON': [],
	'HUAWEI': [],
	'ZTE': [],
	'NOKIA': [],
	'MOTOROLA': [],
	'BODASTAGE': []
}
